//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 11/14/2010 10:31:08 PM
namespace CoasterDBModel35
{
    
    /// <summary>
    /// There are no comments for CoasterDBEntities35 in the schema.
    /// </summary>
    public partial class CoasterDBEntities35 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CoasterDBEntities35 object using the connection string found in the 'CoasterDBEntities35' section of the application configuration file.
        /// </summary>
        public CoasterDBEntities35() : 
                base("name=CoasterDBEntities35", "CoasterDBEntities35")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CoasterDBEntities35 object.
        /// </summary>
        public CoasterDBEntities35(string connectionString) : 
                base(connectionString, "CoasterDBEntities35")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CoasterDBEntities35 object.
        /// </summary>
        public CoasterDBEntities35(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CoasterDBEntities35")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for refCatagories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<refCatagory> refCatagories
        {
            get
            {
                if ((this._refCatagories == null))
                {
                    this._refCatagories = base.CreateQuery<refCatagory>("[refCatagories]");
                }
                return this._refCatagories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<refCatagory> _refCatagories;
        /// <summary>
        /// There are no comments for tblCoasters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<tblCoaster> tblCoasters
        {
            get
            {
                if ((this._tblCoasters == null))
                {
                    this._tblCoasters = base.CreateQuery<tblCoaster>("[tblCoasters]");
                }
                return this._tblCoasters;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<tblCoaster> _tblCoasters;
        /// <summary>
        /// There are no comments for refCatagories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTorefCatagories(refCatagory refCatagory)
        {
            base.AddObject("refCatagories", refCatagory);
        }
        /// <summary>
        /// There are no comments for tblCoasters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTotblCoasters(tblCoaster tblCoaster)
        {
            base.AddObject("tblCoasters", tblCoaster);
        }
    }
    /// <summary>
    /// There are no comments for CoasterDBModel35.refCatagory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CatagoryID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CoasterDBModel35", Name="refCatagory")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class refCatagory : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new refCatagory object.
        /// </summary>
        /// <param name="catagoryID">Initial value of CatagoryID.</param>
        /// <param name="catagoryName">Initial value of CatagoryName.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static refCatagory CreaterefCatagory(int catagoryID, string catagoryName)
        {
            refCatagory refCatagory = new refCatagory();
            refCatagory.CatagoryID = catagoryID;
            refCatagory.CatagoryName = catagoryName;
            return refCatagory;
        }
        /// <summary>
        /// There are no comments for property CatagoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CatagoryID
        {
            get
            {
                return this._CatagoryID;
            }
            set
            {
                this.OnCatagoryIDChanging(value);
                this.ReportPropertyChanging("CatagoryID");
                this._CatagoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CatagoryID");
                this.OnCatagoryIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CatagoryID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatagoryIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatagoryIDChanged();
        /// <summary>
        /// There are no comments for property CatagoryName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CatagoryName
        {
            get
            {
                return this._CatagoryName;
            }
            set
            {
                this.OnCatagoryNameChanging(value);
                this.ReportPropertyChanging("CatagoryName");
                this._CatagoryName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CatagoryName");
                this.OnCatagoryNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CatagoryName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatagoryNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatagoryNameChanged();
    }
    /// <summary>
    /// There are no comments for CoasterDBModel35.tblCoaster in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CoasterID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CoasterDBModel35", Name="tblCoaster")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class tblCoaster : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tblCoaster object.
        /// </summary>
        /// <param name="coasterID">Initial value of CoasterID.</param>
        /// <param name="catagoryID">Initial value of CatagoryID.</param>
        /// <param name="displayOrder">Initial value of DisplayOrder.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="filename">Initial value of Filename.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static tblCoaster CreatetblCoaster(int coasterID, int catagoryID, int displayOrder, string name, string filename)
        {
            tblCoaster tblCoaster = new tblCoaster();
            tblCoaster.CoasterID = coasterID;
            tblCoaster.CatagoryID = catagoryID;
            tblCoaster.DisplayOrder = displayOrder;
            tblCoaster.Name = name;
            tblCoaster.Filename = filename;
            return tblCoaster;
        }
        /// <summary>
        /// There are no comments for property CoasterID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CoasterID
        {
            get
            {
                return this._CoasterID;
            }
            set
            {
                this.OnCoasterIDChanging(value);
                this.ReportPropertyChanging("CoasterID");
                this._CoasterID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CoasterID");
                this.OnCoasterIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CoasterID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCoasterIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCoasterIDChanged();
        /// <summary>
        /// There are no comments for property CatagoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CatagoryID
        {
            get
            {
                return this._CatagoryID;
            }
            set
            {
                this.OnCatagoryIDChanging(value);
                this.ReportPropertyChanging("CatagoryID");
                this._CatagoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CatagoryID");
                this.OnCatagoryIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CatagoryID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatagoryIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatagoryIDChanged();
        /// <summary>
        /// There are no comments for property DisplayOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int DisplayOrder
        {
            get
            {
                return this._DisplayOrder;
            }
            set
            {
                this.OnDisplayOrderChanging(value);
                this.ReportPropertyChanging("DisplayOrder");
                this._DisplayOrder = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DisplayOrder");
                this.OnDisplayOrderChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _DisplayOrder;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDisplayOrderChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDisplayOrderChanged();
        /// <summary>
        /// There are no comments for property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for property Filename in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Filename
        {
            get
            {
                return this._Filename;
            }
            set
            {
                this.OnFilenameChanging(value);
                this.ReportPropertyChanging("Filename");
                this._Filename = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Filename");
                this.OnFilenameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Filename;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFilenameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFilenameChanged();
    }
}
